book:
    title:            "Le développement piloté par le comportement"
    subtitle:         "Partie 1 : Communiquez avec les développeurs"
    author:           "Jean-François Lépine"
    edition:          "First edition"
    language:         fr
    publication_date: ~

    generator: { name: easybook, version: 5.0-DEV }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: toc   }

        - { element: introduction, content: func-introduction.md }
        - { element: chapter, number: 1, content: func-le-besoin-metier.md }
        - { element: chapter, number: 2, content: func-communiquez.md }
        - { element: chapter, number: 3, content: func-impliquez-les-parties-prenantes.md }
        - { element: chapter, number: 4, content: func-exprimez-le-besoin.md }
        - { element: chapter, number: 5, content: func-un-peu-de-recul.md }
        - { element: chapter, number: 6, content: func-recette-maintenabilite.md }
        - { element: chapter, number: 7, content: func-conclusion.md }

        - { element: author, content: author.md }
        - { element: license, content: license.md }



    editions:
        ebook:
            format:         epub
            highlight_code: false
            include_styles: true
            labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       1
                elements:   ["appendix", "chapter", "part"]

        print:
            format:         pdf
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            theme:          CustomJeff
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]

        website:
            extends:        web
            format:         html_chunked
